services:
  valkey:
    image: valkey/valkey:9.1.0-alpine3.23
    ports:
      - '6380:6379'
    healthcheck:
      test: ['CMD', 'valkey-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5

  mongodb:
    image: mongo:8.3
    ports:
      - '27018:27017'
    environment:
      GLIBC_TUNABLES: glibc.pthread.rseq=1
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
