services:
  api:
    profiles: [app]
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    ports:
      - '3000:3000'
    environment:
      PORT: '3000'
      HOST: '0.0.0.0'
      VALKEY_URL: redis://valkey:6379
      MONGODB_URL: mongodb://mongodb:27017/flash_sale
      ORDER_WORKER_IN_PROCESS: 'false'
    depends_on:
      valkey:
        condition: service_healthy
      mongodb:
        condition: service_healthy

  worker:
    profiles: [app]
    build:
      context: .
      dockerfile: Dockerfile
      target: worker
    environment:
      VALKEY_URL: redis://valkey:6379
      MONGODB_URL: mongodb://mongodb:27017/flash_sale
    depends_on:
      valkey:
        condition: service_healthy
      mongodb:
        condition: service_healthy

  web:
    profiles: [app]
    build:
      context: .
      dockerfile: Dockerfile
      target: web
    ports:
      - '8080:80'
    depends_on:
      - api

  valkey:
    image: valkey/valkey:9.1.0-alpine3.23
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'valkey-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5

  mongodb:
    image: mongo:8.3
    ports:
      - '27017:27017'
    environment:
      GLIBC_TUNABLES: glibc.pthread.rseq=1
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
